### ISSUE TITLE
Exception in accidents window

### ISSUE THREAD

**Issue by michbarsinai** [codeworth-gh/KLO-WorkAccidentDB#57]
````
2021-06-07 19:24:20,099 [ERROR] from ErrorHandler in application-akka.actor.default-dispatcher-293 -

! @7k238fdo8 - Internal server error, for (POST) [/bkofc/accidents/] ->

play.api.UnexpectedException: Unexpected exception[NoSuchElementException: key not found: ]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:430)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:422)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:454)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.NoSuchElementException: key not found:
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:225)
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:221)
        at controllers.WorkAccidentCtrl.$anonfun$constructWorkAccident$2(WorkAccidentCtrl.scala:207)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at controllers.WorkAccidentCtrl.constructWorkAccident(WorkAccidentCtrl.scala:207)
        at controllers.WorkAccidentCtrl.$anonfun$doSaveAccident$7(WorkAccidentCtrl.scala:165)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
        ... 12 common frames omitted
````

**Comment by michbarsinai** [comment]
Can't reproduce.
