### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by michbarsinai** [codeworth-gh/KLO-WorkAccidentDB#73]
```
! @83k8lejlh - Internal server error, for (GET) [/safetyWarrants/execs/%D7%A0%D7%A2%D7%9E%D7%9F%20%D7%90%D7%99%D7%AA%D7%9F%20%D7%97%D7%91%D7%A8%D7%94%20%D
play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: empty.max]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
Caused by: java.lang.UnsupportedOperationException: empty.max
        at scala.collection.IterableOnceOps.max(IterableOnce.scala:945)
        at scala.collection.IterableOnceOps.max$(IterableOnce.scala:943)
        at scala.collection.AbstractIterable.max(Iterable.scala:926)
        at views.html.publicside.safetywarrants.execDetails$.extraBottom$1(execDetails.template.scala:55)
        at views.html.publicside.safetywarrants.execDetails$.apply(execDetails.template.scala:67)
        at controllers.PublicCtrl.$anonfun$safetyWarrantsForExec$3(PublicCtrl.scala:286)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)

```

**Comment by michbarsinai** [comment]
Can't reproduce this at the moment
