### ISSUE TITLE
Problem in getting a warrant 

### ISSUE THREAD

**Issue by michbarsinai** [codeworth-gh/KLO-WorkAccidentDB#80]
````
968148]: [error] ErrorHandler -
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: ! @855lmc466 - Internal server error, for (GET) [/safetyWarrants/execs/%D7%9E%D7%A8%D7%99%2520-%2520%D7%97%D7%91%D7%A8%D7%94%2520%D7%A7%D7%91%D7%9C%D7%A0%D7%99%D7%AA%2520%D7%9C%D7%A2%D7%91%D7%95%D7%93%D7%95%D7%AA%2520%D7%91%D7%A0%D7%99%D>
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: empty.max]
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:384)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:482)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at play.core.server.PekkoHttpServer$$anonfun$invokeAction$1$1.applyOrElse(PekkoHttpServer.scala:474)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: Caused by: java.lang.UnsupportedOperationException: empty.max
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.collection.IterableOnceOps.max(IterableOnce.scala:1013)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.collection.IterableOnceOps.max$(IterableOnce.scala:1010)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.collection.AbstractIterable.max(Iterable.scala:933)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at views.html.publicside.safetywarrants.execDetails$.extraBottom$1(execDetails.template.scala:55)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at views.html.publicside.safetywarrants.execDetails$.apply(execDetails.template.scala:67)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at controllers.PublicCtrl.$anonfun$safetyWarrantsForExec$3(PublicCtrl.scala:304)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: [error] ErrorHandler - [587e45f4-70ac-4428-a3c5-6d8547710e1f] play-id:855lmc466
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: [error] ErrorHandler - [587e45f4-70ac-4428-a3c5-6d8547710e1f] title:Unexpected exception
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: [error] ErrorHandler - [587e45f4-70ac-4428-a3c5-6d8547710e1f] description:UnsupportedOperationException: empty.max
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: [error] ErrorHandler - [587e45f4-70ac-4428-a3c5-6d8547710e1f] cause:
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]: java.lang.UnsupportedOperationException: empty.max
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.collection.IterableOnceOps.max(IterableOnce.scala:1013)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.collection.IterableOnceOps.max$(IterableOnce.scala:1010)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.collection.AbstractIterable.max(Iterable.scala:933)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at views.html.publicside.safetywarrants.execDetails$.extraBottom$1(execDetails.template.scala:55)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at views.html.publicside.safetywarrants.execDetails$.apply(execDetails.template.scala:67)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at controllers.PublicCtrl.$anonfun$safetyWarrantsForExec$3(PublicCtrl.scala:304)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
Apr 08 15:38:42 work-accidents.kavlaoved.org.il work-accident-database[968148]:         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Apr 08 15:40:18 work-accidents.kavlaoved.org.il work-accident-database[968148]: [warn] c.PublicCtrl - public-main actually rendered.

````

**Comment by michbarsinai** [comment]
solved by ac048f2
